//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.BL.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fishing.BL.Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string ARCTICCHAR_DESCRIPTION {
            get {
                return ResourceManager.GetString("ARCTICCHAR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки.Кренки и вертушки. Обитает на предпочтительно на поверхности..
        /// </summary>
        internal static string ASP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ASP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине. Клюёт в основном ночью, и утром..
        /// </summary>
        internal static string BURBOT_DESCRIPTION {
            get {
                return ResourceManager.GetString("BURBOT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки.Кренки и вертушки. Обитает на предпочтительно на поверхности. .
        /// </summary>
        internal static string CHUB_DESCRIPTION {
            get {
                return ResourceManager.GetString("CHUB_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string GRAYLING_DESCRIPTION {
            get {
                return ResourceManager.GetString("GRAYLING_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначена наживка.
        /// </summary>
        internal static string NO_BAIT_EQUIPED {
            get {
                return ResourceManager.GetString("NO_BAIT_EQUIPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначена приманка.
        /// </summary>
        internal static string NO_LURE_EQUIPED {
            get {
                return ResourceManager.GetString("NO_LURE_EQUIPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищиник. Предпочитает мелкие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string PERCH_DESCRIPTION {
            get {
                return ResourceManager.GetString("PERCH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на любой глубине..
        /// </summary>
        internal static string PIKE_DESCRIPTION {
            get {
                return ResourceManager.GetString("PIKE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на предпочтительно большой глубине..
        /// </summary>
        internal static string PINKSALMON_DESCRIPTION {
            get {
                return ResourceManager.GetString("PINKSALMON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на предпочтительно большой глубине..
        /// </summary>
        internal static string SALMON_DESCRIPTION {
            get {
                return ResourceManager.GetString("SALMON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает большие и средние приманки. Обитает на маленькой глубине..
        /// </summary>
        internal static string SNAKEHEAD_DESCRIPTION {
            get {
                return ResourceManager.GetString("SNAKEHEAD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string TROUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TROUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хищник. Предпочитает мелкие и средние приманки. Обитает на предпочтительно большой  глубине..
        /// </summary>
        internal static string ZANDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("ZANDER_DESCRIPTION", resourceCulture);
            }
        }
    }
}
